version: "3"
services:
  searcher:
    build:
      context: .
    image: severstal-parser-searcher:latest
    ports:
      - "8080:8080"
    volumes:
      - playwright:/root/.cache/ms-playwright
    environment:
      GRPC_DATA_SERVICE_HOST: "26.29.18.232"
      GRPC_DATA_SERVICE_PORT: "9090"

volumes:
  playwright:
