version: '3'
services:
  searcher:
    build:
      context: .
    image: severstal-parser-searcher:latest
    ports:
      - "8080:8080"
    volumes:
      - playwright:/root/.cache/ms-playwright

volumes:
  playwright: