spring:
  application:
    name: severstal

grpc:
  data-service:
    host: 26.29.18.232
    port: 8080

#dataservice:


#logging.level.ru.mazhanchiki.severstal = TRACE
#logging.file.name = trace.log
#logging.pattern.file = %d [%level] %c{1.0} [%t] %m%n

